### PR TITLE
Added support for multiple snapshots

### PR DESCRIPTION
**Pull request by Almaz5200**
Modified snapshot parsing method to allow for more than one snapshot in test

Example:
Our snapshots look like that
```        
        assertSnapshot(
            matching: light,
            as: .image(on: .iPhone13),
            named: "light"
        )
        assertSnapshot(
            matching: dark,
            as: .image(on: .iPhone13),
            named: "dark"
        )
```

### CODE REVIEW

**Comment by Almaz5200** [comment]
unfortunately I can't find "light" and "dark" names in the report for some reason, that's why I opted to just adding numbers at the end

**Review by wojciech-kulik — APPROVED** [review]
Thank you for the fix! I forgot about this case :D

**Comment by wojciech-kulik** [comment]
There was one problem. On macOS there are no names like reference, failed or difference. I fixed that here: fe422b8a464b90b4c319ff3db9650236199b255f

**Comment by Almaz5200** [comment]
Oh, didn't know that. Thanks! My current projects are all iOS only so I wouldn't catch that

**Pull request merged**
